sudo: required

env:
  - VERSION=ozone HADOOP_VERSION=ozone VERSION=2.3.0 URL=https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz
  - VERSION=2.3.0-hadoop3.0 URL=https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz

services:
   - docker

script:
   - make build

after_success:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - make deploy
